# Header
navbar_brand: false
menu:
  Home: index.html
  Archives: archives/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
widgets:
- about         # See also: `about_content`
- category
- tag
- tagcloud
- archive
- recent_posts
about_widget_content: >
  <p>This is <b>DEMO Site</b> for how to use <a href="https://hexo.io/">hexo</a> with <a href="https://orgmode.org">org-mode</a>.
  For more info, please see this project's <a href="https://github.com/coldnew/hexo-org-example">REAME.md</a>.</p>

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-42122243-1
favicon:
twitter_id:
google_plus: https://plus.google.com/u/0/106837301382084981260/posts
fb_admins:
fb_app_id:

# Disqus
disqus_shortname: coldnew